service: telegramlambdascratch

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  environment:
    TELEGRAM_HELLO_WORLD_KEY: ${env:TELEGRAM_HELLO_WORLD_KEY}

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: helloWorld
          method: post
          cors: true

